-- AlterTable
ALTER TABLE `anomalies` MODIFY `type` ENUM('HIGH_VALUE_CANCELLATION', 'TRANSFER_VELOCITY', 'UNAUTHORIZED_HOLDING_ACCESS', 'UNUSUAL_EXPENSE_SPIKE', 'LOW_STOCK', 'EXPIRING_INVENTORY') NOT NULL;

-- AlterTable
ALTER TABLE `brand_configs` ADD COLUMN `aboutCtaContent` TEXT NULL,
    ADD COLUMN `aboutCtaPrimary` VARCHAR(191) NULL,
    ADD COLUMN `aboutCtaPrimaryLink` VARCHAR(191) NULL,
    ADD COLUMN `aboutCtaSecondary` VARCHAR(191) NULL,
    ADD COLUMN `aboutCtaSecondaryLink` VARCHAR(191) NULL,
    ADD COLUMN `aboutCtaTitle` VARCHAR(191) NULL,
    ADD COLUMN `aboutHeroSubtitle` TEXT NULL,
    ADD COLUMN `aboutHeroTitle` VARCHAR(191) NULL,
    ADD COLUMN `aboutStoryContent` JSON NULL,
    ADD COLUMN `aboutStoryImage` VARCHAR(191) NULL,
    ADD COLUMN `aboutStoryTitle` VARCHAR(191) NULL,
    ADD COLUMN `aboutValuesList` JSON NULL,
    ADD COLUMN `aboutValuesTitle` VARCHAR(191) NULL,
    ADD COLUMN `ctaButtonText` VARCHAR(191) NULL DEFAULT 'Pesan via WhatsApp',
    ADD COLUMN `ctaSectionSubtitle` VARCHAR(191) NULL DEFAULT 'Pesan sekarang via WhatsApp...',
    ADD COLUMN `ctaSectionTitle` VARCHAR(191) NULL DEFAULT 'Siap Menjamu Keluarga Hari Ini?',
    ADD COLUMN `ctaTagline` VARCHAR(191) NULL,
    ADD COLUMN `default_overhead_per_unit` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `featuredSectionSubtitle` TEXT NULL,
    ADD COLUMN `featuredSectionTitle` TEXT NULL,
    ADD COLUMN `featuredTagline` TEXT NULL,
    ADD COLUMN `heroCtaPrimary` TEXT NULL,
    ADD COLUMN `heroCtaPrimaryLink` TEXT NULL,
    ADD COLUMN `heroCtaSecondary` TEXT NULL,
    ADD COLUMN `heroCtaSecondaryLink` TEXT NULL,
    ADD COLUMN `heroImage` TEXT NULL,
    ADD COLUMN `heroTagline` TEXT NULL,
    ADD COLUMN `howToOrderCtaPrimary` VARCHAR(191) NULL DEFAULT 'Buka Katalog Menu',
    ADD COLUMN `howToOrderCtaPrimaryLink` VARCHAR(191) NULL DEFAULT '/rasa-ibu/products',
    ADD COLUMN `howToOrderCtaSecondary` VARCHAR(191) NULL DEFAULT 'Tanya Ongkir',
    ADD COLUMN `howToOrderCtaTitle` VARCHAR(191) NULL DEFAULT 'Katalog Siap Ditelusuri',
    ADD COLUMN `howToOrderHeroSubtitle` VARCHAR(191) NULL DEFAULT 'Kami memilih untuk melayani Anda secara personal via WhatsApp...',
    ADD COLUMN `howToOrderHeroTitle` VARCHAR(191) NULL DEFAULT 'Mudah & Personal.',
    ADD COLUMN `howToOrderInfoImage` VARCHAR(191) NULL,
    ADD COLUMN `howToOrderInfoList` JSON NULL,
    ADD COLUMN `howToOrderInfoTitle` VARCHAR(191) NULL DEFAULT 'Penting Untuk Diketahui',
    ADD COLUMN `howToOrderSteps` JSON NULL,
    ADD COLUMN `marketplace_fee_rate` DOUBLE NOT NULL DEFAULT 0.15,
    ADD COLUMN `philosophyContent` TEXT NULL,
    ADD COLUMN `philosophyImage` TEXT NULL,
    ADD COLUMN `philosophyLinkText` TEXT NULL,
    ADD COLUMN `philosophyLinkUrl` TEXT NULL,
    ADD COLUMN `philosophyTagline` TEXT NULL,
    ADD COLUMN `philosophyTitle` TEXT NULL,
    ADD COLUMN `platformLinks` JSON NULL,
    ADD COLUMN `platformSectionSubtitle` TEXT NULL,
    ADD COLUMN `platformSectionTitle` TEXT NULL,
    ADD COLUMN `platformTagline` TEXT NULL,
    ADD COLUMN `publicNavLinks` JSON NULL,
    ADD COLUMN `publicSubtitle` TEXT NULL,
    ADD COLUMN `publicTitle` TEXT NULL,
    ADD COLUMN `target_monthly_volume` INTEGER NOT NULL DEFAULT 100,
    ADD COLUMN `target_net_margin_rate` DOUBLE NOT NULL DEFAULT 0.30,
    ADD COLUMN `trustBadges` JSON NULL;

-- AlterTable
ALTER TABLE `frozen_variants` ADD COLUMN `marketplace_fee_rate` DECIMAL(5, 4) NULL DEFAULT 0.1500,
    ADD COLUMN `operational_cost_per_unit` DECIMAL(12, 2) NULL,
    ADD COLUMN `selling_price` DECIMAL(12, 2) NULL,
    ADD COLUMN `target_margin` DECIMAL(5, 4) NULL DEFAULT 0.3000;

-- AlterTable
ALTER TABLE `recipe_items` ADD COLUMN `unit` VARCHAR(191) NOT NULL DEFAULT 'gram';
