// Enterprise Audit Export - CSV and PDF export with brand isolation
// CRITICAL: Time-range filtering, brand isolation enforced

import { prisma } from '@/lib/prisma';

/**
 * Audit export request
 */
export interface AuditExportRequest {
    brandId: string;
    startDate: Date;
    endDate: Date;
    format: 'csv' | 'pdf';
    includeExecutions?: boolean;
    includeApprovals?: boolean;
    includeOverrides?: boolean;
    includeRollbacks?: boolean;
}

/**
 * Export audit logs to CSV
 */
export async function exportAuditCSV(
    request: AuditExportRequest
): Promise<string> {
    // Fetch audit logs with brand isolation
    const logs = await fetchAuditLogs(request);

    // Build CSV header
    const header = [
        'Timestamp',
        'Event Type',
        'Performed By',
        'Rule ID',
        'Action ID',
        'Execution ID',
        'Status',
        'Risk Level',
        'Financial Impact',
        'Details'
    ].join(',');

    // Build CSV rows
    const rows = logs.map(log => {
        const metadata = log.metadata as any;

        return [
            log.timestamp.toISOString(),
            log.eventType,
            log.performedBy,
            metadata?.ruleId || '',
            metadata?.actionId || '',
            metadata?.executionId || '',
            metadata?.status || '',
            metadata?.riskLevel || '',
            metadata?.financialImpact || '',
            JSON.stringify(metadata).replace(/"/g, '""') // Escape quotes
        ].join(',');
    }).join('\n');

    return `${header}\n${rows}`;
}

/**
 * Export audit logs to PDF
 */
export async function exportAuditPDF(
    request: AuditExportRequest
): Promise<Buffer> {
    // Fetch audit logs with brand isolation
    const logs = await fetchAuditLogs(request);

    // Build PDF content (simplified - in production use PDF library)
    const content = `
AUDIT REPORT
Brand ID: ${request.brandId}
Period: ${request.startDate.toISOString()} - ${request.endDate.toISOString()}
Generated: ${new Date().toISOString()}

SUMMARY:
- Total Events: ${logs.length}
- Executions: ${logs.filter(l => l.eventType.includes('execution')).length}
- Approvals: ${logs.filter(l => l.eventType.includes('approval')).length}
- Overrides: ${logs.filter(l => l.eventType.includes('override')).length}
- Rollbacks: ${logs.filter(l => l.eventType.includes('rollback')).length}

DETAILED LOG:
${logs.map((log, i) => `
${i + 1}. ${log.timestamp.toISOString()} - ${log.eventType}
   Performed By: ${log.performedBy}
   Details: ${JSON.stringify(log.metadata, null, 2)}
`).join('\n')}

---
This report is generated by ACHIERA Autonomous Analytics.
All data is brand-isolated and auditable.
  `.trim();

    // In production, convert to actual PDF using library like pdfkit
    return Buffer.from(content, 'utf-8');
}

/**
 * Fetch audit logs with brand isolation
 */
async function fetchAuditLogs(
    request: AuditExportRequest
): Promise<any[]> {
    const where: any = {
        brandId: request.brandId, // CRITICAL: Brand isolation
        timestamp: {
            gte: request.startDate,
            lte: request.endDate
        }
    };

    // Filter by event types
    const eventTypes: string[] = [];

    if (request.includeExecutions) {
        eventTypes.push('execution_started', 'execution_completed', 'execution_failed');
    }

    if (request.includeApprovals) {
        eventTypes.push('approval_requested', 'approval_granted', 'approval_rejected');
    }

    if (request.includeOverrides) {
        eventTypes.push('manual_override', 'rule_downgraded', 'level3_kill_switch');
    }

    if (request.includeRollbacks) {
        eventTypes.push('rollback_executed', 'auto_rollback_triggered');
    }

    if (eventTypes.length > 0) {
        where.eventType = { in: eventTypes };
    }

    return await prisma.auditLog.findMany({
        where,
        orderBy: { timestamp: 'asc' },
        take: 10000 // Limit to prevent memory issues
    });
}

/**
 * Export execution summary
 */
export async function exportExecutionSummary(
    brandId: string,
    startDate: Date,
    endDate: Date
): Promise<string> {
    const executions = await prisma.executionLog.findMany({
        where: {
            brandId,
            executedAt: {
                gte: startDate,
                lte: endDate
            }
        },
        orderBy: { executedAt: 'asc' }
    });

    const header = [
        'Execution ID',
        'Rule ID',
        'Action ID',
        'Executed At',
        'Status',
        'Risk Level',
        'Estimated Impact',
        'Actual Impact',
        'Rollback Status',
        'Snapshot ID'
    ].join(',');

    const rows = executions.map(e => {
        const auditData = e.auditData as any;
        const preMetrics = e.preMetrics as any;
        const postMetrics = e.postMetrics as any;

        return [
            e.id,
            e.ruleId,
            e.actionId,
            e.executedAt.toISOString(),
            e.executionStatus,
            auditData?.riskLevel || '',
            preMetrics?.estimated_impact || '',
            postMetrics?.actual_impact || '',
            e.rollbackStatus || '',
            e.snapshotId || ''
        ].join(',');
    }).join('\n');

    return `${header}\n${rows}`;
}
